httpProxy: "http://127.0.0.1:7890"

httpsProxy: "http://127.0.0.1:7890"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js
